### ISSUE TITLE
Using "quarkus-micrometer" cannot initial service

### ISSUE THREAD

**Issue by nijuichien** [quarkiverse/quarkus-neo4j#265]
It's everything good when the service using "quarkus-smallrye-metrics".
But "quarkus-smallrye-metrics" will be deprecated in the future.

And official provide the other dependencies: "quarkus-micrometer" and "quarkus-micrometer-registry-prometheus".
So I change it and get the belowing:
```shell
[2024-06-28T16:48:19.983] [Quarkus Main Thread-262] [ERROR] [io.quarkus.runtime.ApplicationLifecycleManager] [trace_id=, span_id=] Failed to start application (with profile [dev]): java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:113)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.function.Consumer.accept(Object)" because "consumer" is null
	at io.quarkus.micrometer.runtime.MicrometerRecorder.registerMetrics(MicrometerRecorder.java:229)
	at io.quarkus.deployment.steps.MicrometerProcessor$configureRegistry477897979.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.MicrometerProcessor$configureRegistry477897979.deploy(Unknown Source)
	... 13 more
```

But I don't know what happened and how to resolve it.

**Comment by michael-simons** [comment]
Hi @nijuichien In the stack trace I cannot see how this relates to the Neo4j extensions. Can you pleas share the full stack or code?

**Comment by michael-simons** [comment]
I found the bug, thanks for the report. Will be fixed soon, release will follow.

**Comment by michael-simons** [comment]
@all-contributors please add @nijuichien for error

**Comment by michael-simons** [comment]
@all-contributors please add @nijuichien for bug

**Comment by nijuichien** [comment]
I'm glad that i was be a contributor for the issue. Honestly I have no ability to found that root cause and resolve it. I just depend them and found that issue. Last I am very appreciated you resolved it quickly. Thank you.

**Comment by michael-simons** [comment]
You most welcome. And I think taking the time and write a report is a valuable contribution! Best of success in what you are doing 👍

**Comment by michael-simons** [comment]
Aaah and before I forget: If you can't upgrade right now, things should work with the previous release as soon as you enable Neo4j driver metrics via [quarkus.neo4j.pool.metrics.enabled](https://docs.quarkiverse.io/quarkus-neo4j/dev/index.html#quarkus-neo4j_quarkus-neo4j-pool-metrics-enabled)
