### ISSUE TITLE
Native build fails on GraalVM 17.

### ISSUE THREAD

**Issue by michael-simons** [quarkiverse/quarkus-neo4j#313]
I use to trust the GitHub actions for the native image build and things have been consistently green, for JVM but also native image. I just realised through our internal testing that since Quarkus 3.17 the native build fails on GraalVM 17.

For convenience, I already traced class initialisation for and I find myself confused, as I explicitly defer the offenders to runtime here:

https://github.com/quarkiverse/quarkus-neo4j/blob/fc4240301d28a88d075d82f7aa1edf1d80643a08/deployment/src/main/java/io/quarkus/neo4j/deployment/Neo4jDriverProcessor.java#L61-L91

```
[2/8] Performing analysis...  [*]                                                                       (46,4s @ 6,38GB)
  14.443 (87,80%) of 16.449 types reachable
  21.046 (59,57%) of 35.332 fields reachable
  80.263 (61,16%) of 131.238 methods reachable
   4.402 types,   423 fields, and 4.597 methods registered for reflection
       1 native library: -framework CoreServices

Error: Classes that should be initialized at run time got initialized during image building:
 io.vertx.core.buffer.impl.VertxHeapByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). io.vertx.core.eventbus.impl.clustered.ClusteredEventBus caused initialization of this class with the following trace: 
	at io.vertx.core.buffer.impl.VertxHeapByteBuf.<clinit>(VertxHeapByteBuf.java)
	at io.vertx.core.buffer.impl.VertxByteBufAllocator$2.newHeapBuffer(VertxByteBufAllocator.java:44)
	at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:169)
	at io.vertx.core.buffer.impl.BufferImpl.<init>(BufferImpl.java:76)
	at io.vertx.core.buffer.impl.BufferImpl.buffer(BufferImpl.java:58)
	at io.vertx.core.buffer.Buffer.buffer(Buffer.java:94)
	at io.vertx.core.eventbus.impl.clustered.ClusteredEventBus.<clinit>(ClusteredEventBus.java:63)

io.netty.buffer.UnpooledHeapByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). org.neo4j.driver.internal.bolt.basicimpl.async.connection.BoltProtocolUtil caused initialization of this class with the following trace: 
	at io.netty.buffer.UnpooledHeapByteBuf.<clinit>(UnpooledHeapByteBuf.java)
	at io.netty.buffer.UnpooledByteBufAllocator.newHeapBuffer(UnpooledByteBufAllocator.java:82)
	at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:169)
	at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:160)
	at io.netty.buffer.Unpooled.buffer(Unpooled.java:119)
	at io.netty.buffer.Unpooled.copyInt(Unpooled.java:719)
	at org.neo4j.driver.internal.bolt.basicimpl.async.connection.BoltProtocolUtil.<clinit>(BoltProtocolUtil.java:40)

io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledHeapByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). org.neo4j.driver.internal.bolt.basicimpl.async.connection.BoltProtocolUtil caused initialization of this class with the following trace: 
	at io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledHeapByteBuf.<clinit>(UnpooledByteBufAllocator.java)
	at io.netty.buffer.UnpooledByteBufAllocator.newHeapBuffer(UnpooledByteBufAllocator.java:82)
	at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:169)
	at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:160)
	at io.netty.buffer.Unpooled.buffer(Unpooled.java:119)
	at io.netty.buffer.Unpooled.copyInt(Unpooled.java:719)
	at org.neo4j.driver.internal.bolt.basicimpl.async.connection.BoltProtocolUtil.<clinit>(BoltProtocolUtil.java:40)

io.netty.buffer.AbstractReferenceCountedByteBuf the class was requested to be initialized at run time (from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///Users/msimons/Projects/quarkiverse/quarkus-neo4j/integration-tests/target/quarkus-neo4j-integration-tests-5.0.1-SNAPSHOT-native-image-source-jar/lib/io.netty.netty-buffer-4.1.115.Final.jar' with 'io.netty.buffer.AbstractReferenceCountedByteBuf'). org.neo4j.driver.internal.bolt.basicimpl.async.connection.BoltProtocolUtil caused initialization of this class with the following trace: 
	at io.netty.buffer.AbstractReferenceCountedByteBuf.<clinit>(AbstractReferenceCountedByteBuf.java:27)
	at io.netty.buffer.UnpooledByteBufAllocator.newHeapBuffer(UnpooledByteBufAllocator.java:82)
	at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:169)
	at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:160)
	at io.netty.buffer.Unpooled.buffer(Unpooled.java:119)
	at io.netty.buffer.Unpooled.copyInt(Unpooled.java:719)
	at org.neo4j.driver.internal.bolt.basicimpl.async.connection.BoltProtocolUtil.<clinit>(BoltProtocolUtil.java:40)

io.netty.buffer.ByteBufUtil the class was requested to be initialized at run time (from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///Users/msimons/Projects/quarkiverse/quarkus-neo4j/integration-tests/target/quarkus-neo4j-integration-tests-5.0.1-SNAPSHOT-native-image-source-jar/lib/io.netty.netty-buffer-4.1.115.Final.jar' with 'io.netty.buffer.ByteBufUtil'). io.netty.handler.ssl.JdkSslServerContext caused initialization of this class with the following trace: 
	at io.netty.buffer.ByteBufUtil.<clinit>(ByteBufUtil.java:60)
	at io.netty.buffer.Unpooled.copiedBufferAscii(Unpooled.java:615)
	at io.netty.buffer.Unpooled.copiedBuffer(Unpooled.java:586)
	at io.netty.handler.ssl.PemReader.readCertificates(PemReader.java:98)
	at io.netty.handler.ssl.SslContext.toX509Certificates(SslContext.java:1278)
	at io.netty.handler.ssl.JdkSslServerContext.checkIfWrappingTrustManagerIsSupported(JdkSslServerContext.java:81)
	at io.netty.handler.ssl.JdkSslServerContext.<clinit>(JdkSslServerContext.java:66)

io.netty.buffer.PooledByteBufAllocator the class was requested to be initialized at run time (from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///Users/msimons/Projects/quarkiverse/quarkus-neo4j/integration-tests/target/quarkus-neo4j-integration-tests-5.0.1-SNAPSHOT-native-image-source-jar/lib/io.netty.netty-buffer-4.1.115.Final.jar' with 'io.netty.buffer.PooledByteBufAllocator'). io.vertx.core.buffer.impl.VertxByteBufAllocator caused initialization of this class with the following trace: 
	at io.netty.buffer.PooledByteBufAllocator.<clinit>(PooledByteBufAllocator.java:38)
	at io.vertx.core.buffer.impl.VertxByteBufAllocator.<clinit>(VertxByteBufAllocator.java:27)


com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 io.vertx.core.buffer.impl.VertxHeapByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). io.vertx.core.eventbus.impl.clustered.ClusteredEventBus caused initialization of this class with the following trace: 
	at io.vertx.core.buffer.impl.VertxHeapByteBuf.<clinit>(VertxHeapByteBuf.java)
	at io.vertx.core.buffer.impl.VertxByteBufAllocator$2.newHeapBuffer(VertxByteBufAllocator.java:44)
	at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:169)
	at io.vertx.core.buffer.impl.BufferImpl.<init>(BufferImpl.java:76)
	at io.vertx.core.buffer.impl.BufferImpl.buffer(BufferImpl.java:58)
	at io.vertx.core.buffer.Buffer.buffer(Buffer.java:94)
	at io.vertx.core.eventbus.impl.clustered.ClusteredEventBus.<clinit>(ClusteredEventBus.java:63)

io.netty.buffer.UnpooledHeapByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). org.neo4j.driver.internal.bolt.basicimpl.async.connection.BoltProtocolUtil caused initialization of this class with the following trace: 
	at io.netty.buffer.UnpooledHeapByteBuf.<clinit>(UnpooledHeapByteBuf.java)
	at io.netty.buffer.UnpooledByteBufAllocator.newHeapBuffer(UnpooledByteBufAllocator.java:82)
	at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:169)
	at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:160)
	at io.netty.buffer.Unpooled.buffer(Unpooled.java:119)
	at io.netty.buffer.Unpooled.copyInt(Unpooled.java:719)
	at org.neo4j.driver.internal.bolt.basicimpl.async.connection.BoltProtocolUtil.<clinit>(BoltProtocolUtil.java:40)

io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledHeapByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). org.neo4j.driver.internal.bolt.basicimpl.async.connection.BoltProtocolUtil caused initialization of this class with the following trace: 
	at io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledHeapByteBuf.<clinit>(UnpooledByteBufAllocator.java)
	at io.netty.buffer.UnpooledByteBufAllocator.newHeapBuffer(UnpooledByteBufAllocator.java:82)
	at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:169)
	at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:160)
	at io.netty.buffer.Unpooled.buffer(Unpooled.java:119)
	at io.netty.buffer.Unpooled.copyInt(Unpooled.java:719)
	at org.neo4j.driver.internal.bolt.basicimpl.async.connection.BoltProtocolUtil.<clinit>(BoltProtocolUtil.java:40)

io.netty.buffer.AbstractReferenceCountedByteBuf the class was requested to be initialized at run time (from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///Users/msimons/Projects/quarkiverse/quarkus-neo4j/integration-tests/target/quarkus-neo4j-integration-tests-5.0.1-SNAPSHOT-native-image-source-jar/lib/io.netty.netty-buffer-4.1.115.Final.jar' with 'io.netty.buffer.AbstractReferenceCountedByteBuf'). org.neo4j.driver.internal.bolt.basicimpl.async.connection.BoltProtocolUtil caused initialization of this class with the following trace: 
	at io.netty.buffer.AbstractReferenceCountedByteBuf.<clinit>(AbstractReferenceCountedByteBuf.java:27)
	at io.netty.buffer.UnpooledByteBufAllocator.newHeapBuffer(UnpooledByteBufAllocator.java:82)
	at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:169)
	at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:160)
	at io.netty.buffer.Unpooled.buffer(Unpooled.java:119)
	at io.netty.buffer.Unpooled.copyInt(Unpooled.java:719)
	at org.neo4j.driver.internal.bolt.basicimpl.async.connection.BoltProtocolUtil.<clinit>(BoltProtocolUtil.java:40)

io.netty.buffer.ByteBufUtil the class was requested to be initialized at run time (from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///Users/msimons/Projects/quarkiverse/quarkus-neo4j/integration-tests/target/quarkus-neo4j-integration-tests-5.0.1-SNAPSHOT-native-image-source-jar/lib/io.netty.netty-buffer-4.1.115.Final.jar' with 'io.netty.buffer.ByteBufUtil'). io.netty.handler.ssl.JdkSslServerContext caused initialization of this class with the following trace: 
	at io.netty.buffer.ByteBufUtil.<clinit>(ByteBufUtil.java:60)
	at io.netty.buffer.Unpooled.copiedBufferAscii(Unpooled.java:615)
	at io.netty.buffer.Unpooled.copiedBuffer(Unpooled.java:586)
	at io.netty.handler.ssl.PemReader.readCertificates(PemReader.java:98)
	at io.netty.handler.ssl.SslContext.toX509Certificates(SslContext.java:1278)
	at io.netty.handler.ssl.JdkSslServerContext.checkIfWrappingTrustManagerIsSupported(JdkSslServerContext.java:81)
	at io.netty.handler.ssl.JdkSslServerContext.<clinit>(JdkSslServerContext.java:66)

io.netty.buffer.PooledByteBufAllocator the class was requested to be initialized at run time (from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///Users/msimons/Projects/quarkiverse/quarkus-neo4j/integration-tests/target/quarkus-neo4j-integration-tests-5.0.1-SNAPSHOT-native-image-source-jar/lib/io.netty.netty-buffer-4.1.115.Final.jar' with 'io.netty.buffer.PooledByteBufAllocator'). io.vertx.core.buffer.impl.VertxByteBufAllocator caused initialization of this class with the following trace: 
	at io.netty.buffer.PooledByteBufAllocator.<clinit>(PooledByteBufAllocator.java:38)
	at io.vertx.core.buffer.impl.VertxByteBufAllocator.<clinit>(VertxByteBufAllocator.java:27)


	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:73)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ProvenSafeClassInitializationSupport.checkDelayedInitialization(ProvenSafeClassInitializationSupport.java:277)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:164)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$10(NativeImageGenerator.java:770)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:89)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$11(NativeImageGenerator.java:770)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.AbstractAnalysisEngine.runAnalysis(AbstractAnalysisEngine.java:179)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:767)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:582)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:539)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:408)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:612)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:134)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:94)
```

Any ideas @maxandersen or @gsmet ? I'm ok with the answer being "You need GraalVM 21", and happy to learn I missed the announcement about that somwhere.

FYI @injectives

**Comment by maxandersen** [comment]
@zakkak fyi

**Comment by michael-simons** [comment]
FWIW I am totally fine bumping our internal testing to 21, just got caught by surprise.

**Comment by zakkak** [comment]
@michael-simons if by GraalVM 17 you mean GraalVM for JDK 17 (23.0 internal version), you are right, the answer is you need at least GraalVM for JDK 21 with Quarkus >= 3.8.5.

> happy to learn I missed the announcement about that somwhere.

I don't think Quarkus makes such announcements, @gsmet will know better.

What we did change to make it more intuitive is that we print a warning, so if you check the logs there should be a message like the following:

```
You are using an older version of GraalVM or Mandrel : 23.0.4.0. Quarkus currently supports 23.1.0. Please upgrade to this version.
```

The simplest way to handle this is by using the builder-image provided by Quarkus, see [`quarkus.native.container-build`](https://quarkus.io/guides/all-config#quarkus-core_quarkus-native-container-build) and [`quarkus.native.builder-image`](https://quarkus.io/guides/all-config#quarkus-core_quarkus-native-builder-image) (don't explicitly set this property and Quarkus will use the correct one).

**Comment by michael-simons** [comment]
Thank you all. 

@zakkak We have been internally testing the native build directly on GraalVM for JDK 17 successfully until just lately… We will bump that now.
